// Complete directory of Chilean communes organized by region
// Source: Chilean National Statistics Institute (INE)

export interface ComunaData {
    nombre: string
    region: string
}

export const COMUNAS_POR_REGION: Record<string, string[]> = {
    'Arica y Parinacota': [
        'Arica',
        'Camarones',
        'General Lagos',
        'Putre',
    ],
    'Tarapacá': [
        'Alto Hospicio',
        'Camiña',
        'Colchane',
        'Huara',
        'Iquique',
        'Pica',
        'Pozo Almonte',
    ],
    'Antofagasta': [
        'Antofagasta',
        'Calama',
        'María Elena',
        'Mejillones',
        'Ollagüe',
        'San Pedro de Atacama',
        'Sierra Gorda',
        'Taltal',
        'Tocopilla',
    ],
    'Atacama': [
        'Alto del Carmen',
        'Caldera',
        'Chañaral',
        'Copiapó',
        'Diego de Almagro',
        'Freirina',
        'Huasco',
        'Tierra Amarilla',
        'Vallenar',
    ],
    'Coquimbo': [
        'Andacollo',
        'Canela',
        'Combarbalá',
        'Coquimbo',
        'Illapel',
        'La Higuera',
        'La Serena',
        'Los Vilos',
        'Monte Patria',
        'Ovalle',
        'Paihuano',
        'Punitaqui',
        'Río Hurtado',
        'Salamanca',
        'Vicuña',
    ],
    'Valparaíso': [
        'Algarrobo',
        'Cabildo',
        'Calle Larga',
        'Cartagena',
        'Casablanca',
        'Catemu',
        'Concón',
        'El Quisco',
        'El Tabo',
        'Hijuelas',
        'Isla de Pascua',
        'Juan Fernández',
        'La Calera',
        'La Cruz',
        'La Ligua',
        'Limache',
        'Llaillay',
        'Los Andes',
        'Nogales',
        'Olmué',
        'Panquehue',
        'Papudo',
        'Petorca',
        'Puchuncaví',
        'Putaendo',
        'Quillota',
        'Quilpué',
        'Quintero',
        'Rinconada',
        'San Antonio',
        'San Esteban',
        'San Felipe',
        'Santa María',
        'Santo Domingo',
        'Valparaíso',
        'Villa Alemana',
        'Viña del Mar',
        'Zapallar',
    ],
    'Región Metropolitana': [
        'Alhué',
        'Buin',
        'Calera de Tango',
        'Cerrillos',
        'Cerro Navia',
        'Colina',
        'Conchalí',
        'Curacaví',
        'El Bosque',
        'El Monte',
        'Estación Central',
        'Huechuraba',
        'Independencia',
        'Isla de Maipo',
        'La Cisterna',
        'La Florida',
        'La Granja',
        'La Pintana',
        'La Reina',
        'Lampa',
        'Las Condes',
        'Lo Barnechea',
        'Lo Espejo',
        'Lo Prado',
        'Macul',
        'Maipú',
        'María Pinto',
        'Melipilla',
        'Ñuñoa',
        'Padre Hurtado',
        'Paine',
        'Pedro Aguirre Cerda',
        'Peñaflor',
        'Peñalolén',
        'Pirque',
        'Providencia',
        'Pudahuel',
        'Puente Alto',
        'Quilicura',
        'Quinta Normal',
        'Recoleta',
        'Renca',
        'San Bernardo',
        'San Joaquín',
        'San José de Maipo',
        'San Miguel',
        'San Pedro',
        'San Ramón',
        'Santiago',
        'Talagante',
        'Tiltil',
        'Vitacura',
    ],
    'O\'Higgins': [
        'Chimbarongo',
        'Chépica',
        'Codegua',
        'Coinco',
        'Coltauco',
        'Doñihue',
        'Graneros',
        'La Estrella',
        'Las Cabras',
        'Litueche',
        'Lolol',
        'Machalí',
        'Malloa',
        'Marchigüe',
        'Mostazal',
        'Nancagua',
        'Navidad',
        'Olivar',
        'Palmilla',
        'Paredones',
        'Peralillo',
        'Peumo',
        'Pichidegua',
        'Pichilemu',
        'Placilla',
        'Pumanque',
        'Quinta de Tilcoco',
        'Rancagua',
        'Rengo',
        'Requínoa',
        'San Fernando',
        'San Vicente de Tagua Tagua',
        'Santa Cruz',
    ],
    'Maule': [
        'Cauquenes',
        'Chanco',
        'Colbún',
        'Constitución',
        'Curepto',
        'Curicó',
        'Empedrado',
        'Hualañé',
        'Licantén',
        'Linares',
        'Longaví',
        'Maule',
        'Molina',
        'Parral',
        'Pelarco',
        'Pelluhue',
        'Pencahue',
        'Rauco',
        'Retiro',
        'Río Claro',
        'Romeral',
        'Sagrada Familia',
        'San Clemente',
        'San Javier',
        'San Rafael',
        'Talca',
        'Teno',
        'Vichuquén',
        'Villa Alegre',
        'Yerbas Buenas',
    ],
    'Ñuble': [
        'Bulnes',
        'Chillán',
        'Chillán Viejo',
        'Cobquecura',
        'Coelemu',
        'Coihueco',
        'El Carmen',
        'Ninhue',
        'Ñiquén',
        'Pemuco',
        'Pinto',
        'Portezuelo',
        'Quillón',
        'Quirihue',
        'Ránquil',
        'San Carlos',
        'San Fabián',
        'San Ignacio',
        'San Nicolás',
        'Treguaco',
        'Yungay',
    ],
    'Biobío': [
        'Alto Biobío',
        'Antuco',
        'Arauco',
        'Cabrero',
        'Cañete',
        'Chiguayante',
        'Concepción',
        'Contulmo',
        'Coronel',
        'Curanilahue',
        'Florida',
        'Hualpén',
        'Hualqui',
        'Laja',
        'Lebu',
        'Los Álamos',
        'Los Ángeles',
        'Lota',
        'Mulchén',
        'Nacimiento',
        'Negrete',
        'Penco',
        'Quilaco',
        'Quilleco',
        'San Pedro de la Paz',
        'San Rosendo',
        'Santa Bárbara',
        'Santa Juana',
        'Talcahuano',
        'Tirúa',
        'Tomé',
        'Tucapel',
        'Yumbel',
    ],
    'Araucanía': [
        'Angol',
        'Carahue',
        'Cholchol',
        'Collipulli',
        'Cunco',
        'Curacautín',
        'Curarrehue',
        'Ercilla',
        'Freire',
        'Galvarino',
        'Gorbea',
        'Lautaro',
        'Loncoche',
        'Lonquimay',
        'Los Sauces',
        'Lumaco',
        'Melipeuco',
        'Nueva Imperial',
        'Padre Las Casas',
        'Perquenco',
        'Pitrufquén',
        'Pucón',
        'Purén',
        'Renaico',
        'Saavedra',
        'Temuco',
        'Teodoro Schmidt',
        'Toltén',
        'Traiguén',
        'Victoria',
        'Vilcún',
        'Villarrica',
    ],
    'Los Ríos': [
        'Corral',
        'Futrono',
        'La Unión',
        'Lago Ranco',
        'Lanco',
        'Los Lagos',
        'Máfil',
        'Mariquina',
        'Paillaco',
        'Panguipulli',
        'Río Bueno',
        'Valdivia',
    ],
    'Los Lagos': [
        'Ancud',
        'Calbuco',
        'Castro',
        'Chaitén',
        'Chonchi',
        'Cochamó',
        'Curaco de Vélez',
        'Dalcahue',
        'Fresia',
        'Frutillar',
        'Futaleufú',
        'Hualaihué',
        'Llanquihue',
        'Los Muermos',
        'Maullín',
        'Osorno',
        'Palena',
        'Puerto Montt',
        'Puerto Octay',
        'Puerto Varas',
        'Puqueldón',
        'Purranque',
        'Puyehue',
        'Queilén',
        'Quellón',
        'Quemchi',
        'Quinchao',
        'Río Negro',
        'San Juan de la Costa',
        'San Pablo',
    ],
    'Aysén': [
        'Aysén',
        'Chile Chico',
        'Cisnes',
        'Cochrane',
        'Coyhaique',
        'Guaitecas',
        'Lago Verde',
        'O\'Higgins',
        'Río Ibáñez',
        'Tortel',
    ],
    'Magallanes': [
        'Antártica',
        'Cabo de Hornos',
        'Laguna Blanca',
        'Natales',
        'Porvenir',
        'Primavera',
        'Punta Arenas',
        'Río Verde',
        'San Gregorio',
        'Timaukel',
        'Torres del Paine',
    ],
}

// Flat list of all comunas with their regions
export const TODAS_LAS_COMUNAS: ComunaData[] = Object.entries(COMUNAS_POR_REGION).flatMap(
    ([region, comunas]) => comunas.map(nombre => ({ nombre, region }))
)

// Function to search comunas by partial name
export function buscarComunas(query: string, region?: string): ComunaData[] {
    const queryLower = query.toLowerCase().trim()

    if (!queryLower) return []

    let comunas = TODAS_LAS_COMUNAS

    // Filter by region if specified
    if (region) {
        comunas = comunas.filter(c => c.region === region)
    }

    // Filter by query - match from start or anywhere in the name
    const results = comunas.filter(c =>
        c.nombre.toLowerCase().includes(queryLower)
    )

    // Sort: prioritize matches at the start of the name
    results.sort((a, b) => {
        const aStartsWith = a.nombre.toLowerCase().startsWith(queryLower)
        const bStartsWith = b.nombre.toLowerCase().startsWith(queryLower)

        if (aStartsWith && !bStartsWith) return -1
        if (!aStartsWith && bStartsWith) return 1
        return a.nombre.localeCompare(b.nombre)
    })

    return results.slice(0, 10) // Return max 10 results
}

// Get comunas for a specific region
export function getComunasPorRegion(region: string): string[] {
    return COMUNAS_POR_REGION[region] || []
}
